// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOcD-G-SY7B5mpdy8IOBBw4P6q3vkT20',
    appId: '1:903538549863:web:3160a9d8ff4cfebdf260c2',
    messagingSenderId: '903538549863',
    projectId: 'ecommerce-app-ee7e5',
    authDomain: 'ecommerce-app-ee7e5.firebaseapp.com',
    storageBucket: 'ecommerce-app-ee7e5.firebasestorage.app',
    measurementId: 'G-4HEK7MZ424',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFM6UaUgQ1T2-Ki3w5NU30zxZlIJk8eCQ',
    appId: '1:903538549863:android:d18cd394c350510bf260c2',
    messagingSenderId: '903538549863',
    projectId: 'ecommerce-app-ee7e5',
    storageBucket: 'ecommerce-app-ee7e5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxOcD-G-SY7B5mpdy8IOBBw4P6q3vkT20',
    appId: '1:903538549863:web:8704fccda75da3f1f260c2',
    messagingSenderId: '903538549863',
    projectId: 'ecommerce-app-ee7e5',
    authDomain: 'ecommerce-app-ee7e5.firebaseapp.com',
    storageBucket: 'ecommerce-app-ee7e5.firebasestorage.app',
    measurementId: 'G-VRGZYCHGC5',
  );
}
