// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawpCLkGu4xbqwNpGulacpdk9UHWx6-aY',
    appId: '1:369676573410:web:3030d2c55040b0358bdcbb',
    messagingSenderId: '369676573410',
    projectId: 'ecommerce-app-e7dea',
    authDomain: 'ecommerce-app-e7dea.firebaseapp.com',
    storageBucket: 'ecommerce-app-e7dea.firebasestorage.app',
    measurementId: 'G-3BV2BLKR07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VRAHlCKX5uBMhbF-tkXNBhqjwkSyAwc',
    appId: '1:369676573410:android:324b20d01ef56a818bdcbb',
    messagingSenderId: '369676573410',
    projectId: 'ecommerce-app-e7dea',
    storageBucket: 'ecommerce-app-e7dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDT2XoXkbpK3S305dbKlWw5lGItLZO6q8',
    appId: '1:369676573410:ios:befb3e6d6a429f238bdcbb',
    messagingSenderId: '369676573410',
    projectId: 'ecommerce-app-e7dea',
    storageBucket: 'ecommerce-app-e7dea.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDT2XoXkbpK3S305dbKlWw5lGItLZO6q8',
    appId: '1:369676573410:ios:befb3e6d6a429f238bdcbb',
    messagingSenderId: '369676573410',
    projectId: 'ecommerce-app-e7dea',
    storageBucket: 'ecommerce-app-e7dea.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawpCLkGu4xbqwNpGulacpdk9UHWx6-aY',
    appId: '1:369676573410:web:9ac927d6573793578bdcbb',
    messagingSenderId: '369676573410',
    projectId: 'ecommerce-app-e7dea',
    authDomain: 'ecommerce-app-e7dea.firebaseapp.com',
    storageBucket: 'ecommerce-app-e7dea.firebasestorage.app',
    measurementId: 'G-7BBVVEEXNL',
  );
}